name: ghost-desktop
version: 1.5.0
summary: The professional publishing platform.
description: |
 A beautiful desktop application enabling you to easily manage multiple
 Ghost blogs and work without distractions.
 .
 Ghost is a fully open source, hackable platform for building and
 running a modern online publication. We power blogs, magazines and
 journalists from Zappos to Sky News.

grade: stable
confinement: strict

parts:
  ghost-desktop:
    plugin: dump
    source: https://github.com/TryGhost/Ghost-Desktop/releases/download/v1.5.0/ghost-desktop-1.5.0-debian.deb
    source-type: deb
    # Correct path to icon.
    prepare: |
      sed -i 's|Icon=Ghost|Icon=/usr/share/pixmaps/Ghost\.png|' usr/share/applications/Ghost.desktop
    after:
      - desktop-gtk2
    stage-packages:
      - gconf2
      - libasound2
      - libnotify4
      - libnspr4
      - libnss3
      - libpulse0
      - libxss1
      - libxtst6

apps:
  ghost-desktop:
    # Correct the TMPDIR path for Chromium Framework/Electron to
    # ensure libappindicator has readable resources.
    command: env TMPDIR=$XDG_RUNTIME_DIR ${SNAP}/bin/desktop-launch $SNAP/usr/lib/Ghost/Ghost
    desktop: usr/share/applications/Ghost.desktop
    plugs:
      - browser-support
      - gsettings
      - home
      - mount-observe
      - network
      - pulseaudio
      - unity7
      - x11
