name: ghost-desktop
version: latest
version-script: cat $SNAPCRAFT_STAGE/version
summary: The professional publishing platform.
description: |
 A beautiful desktop application enabling you to easily manage multiple
 Ghost blogs and work without distractions.
 .
 Ghost is a fully open source, hackable platform for building and
 running a modern online publication. We power blogs, magazines and
 journalists from Zappos to Sky News.

grade: stable
confinement: strict

parts:
  ghost-desktop:
    plugin: nil
    override-build: |
      snapcraftctl build
      # Get the latest releases json
      echo "Get GitHub releases..."
      wget --quiet https://api.github.com/repos/TryGhost/Ghost-Desktop/releases/latest -O releases.json

      # Get the version from the tag_name and the download URL.
      VERSION=$(jq . releases.json | grep tag_name | cut -d'"' -f4 | sed s'/v//')
      DEB_URL=$(cat releases.json | jq -r ".assets[] | select(.name | test(\"deb\")) | .browser_download_url")
      DEB=$(basename "${DEB_URL}")

      echo "Downloading ${DEB_URL}..."
      wget --quiet "${DEB_URL}" -O "${SNAPCRAFT_PART_INSTALL}/${DEB}"

      echo "Unpacking ${DEB}..."
      dpkg -x "${SNAPCRAFT_PART_INSTALL}/${DEB}" ${SNAPCRAFT_PART_INSTALL}
      rm -f releases.json 2>/dev/null
      rm -f "${SNAPCRAFT_PART_INSTALL}/${DEB}" 2>/dev/null
      echo $VERSION > $SNAPCRAFT_STAGE/version
      # Correct the Icon path
      sed -i 's|Icon=Ghost|Icon=/usr/share/pixmaps/Ghost\.png|' ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/Ghost.desktop
    after:
      - desktop-gtk2
    build-packages:
      # Ghost Desktop debs are only available for amd64.
      # Fail builds on other architectures
      - on amd64:
        - dpkg
        - jq
        - wget
      - else fail
    stage-packages:
      - libasound2
      - libgconf2-4
      - libnotify4
      - libnspr4
      - libnss3
      - libpulse0
      - libxss1
      - libxtst6

apps:
  ghost-desktop:
    command: bin/desktop-launch $SNAP/usr/lib/Ghost/Ghost
    desktop: usr/share/applications/Ghost.desktop
    # Correct the TMPDIR path for Chromium Framework/Electron to ensure
    # libappindicator has readable resources.
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
    plugs:
      - bluez
      - browser-support
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - mount-observe
      - network
      - opengl
      - pulseaudio
      - unity7
      - wayland
      - x11
